const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const {ContactStateManager}=require('../src/1-state-persistence-fix');const {ParallelCampaignExecutor}=require('../src/2-parallel-processing-fix');const {BrowserManager}=require('../src/3-browser-selection-fix');const {WhatsAppCampaignManager}=require('../src/4-integration-campaign');
(async()=>{let passed=0;const test=async(name,fn)=>{try{await fn();console.log('PASS '+name);passed++}catch(e){console.error('FAIL '+name+' '+e.message);process.exitCode=1}};const dir=fs.mkdtempSync(path.join(os.tmpdir(),'wa-test-'));const file=path.join(dir,'contacts.json');fs.writeFileSync(file,JSON.stringify([{phone:'111',status:'pending'},{phone:'222',status:'pending'}]));
await test('state single update',async()=>{const m=new ContactStateManager(file);await m.updateContactStatus(0,'sent',{lastSentAt:'x'});assert.equal((await m.readContacts())[0].status,'sent')});
await test('state batch update',async()=>{const m=new ContactStateManager(file);await m.batchUpdateStatuses([{index:1,status:'failed',metadata:{error:'x'}}]);const c=await m.readContacts();assert.equal(c[1].status,'failed');assert.equal(c[1].error,'x')});
await test('status summary',async()=>{const s=await new ContactStateManager(file).getStatusSummary();assert.deepEqual(s,{total:2,sent:1,failed:1,pending:0})});
await test('parallel concurrency',async()=>{let active=0,max=0;const e=new ParallelCampaignExecutor({concurrency:3});await e.executeWithConcurrency(Array.from({length:8},()=>async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;}));assert(max<=3)});
await test('parallel retry',async()=>{let n=0;const e=new ParallelCampaignExecutor({concurrency:1,maxRetries:2,retryDelay:1});const r=await e.sendMessagesParallel([1],async()=>{if(n++<2)throw new Error('temporary');return 1});assert.equal(r[0].status,'sent');assert.equal(n,3)});
await test('browser detection',async()=>{const b=BrowserManager.detectInstalledBrowsers();assert(['chromium','chrome','edge'].every(k=>Object.prototype.hasOwnProperty.call(b,k)))});
await test('browser switch',async()=>{const b=new BrowserManager({browser:'chromium'});const i=await b.switchBrowser('chrome');assert.equal(i.browser,'chrome')});
await test('campaign integration',async()=>{const m=new WhatsAppCampaignManager({contactsFile:file,concurrency:2,browser:'chromium'});await m.initialize();const report=await m.runCampaign(async()=>true);assert.equal(report.contactStats.sent,2)});
console.log('RESULT '+passed+'/8 passed');if(passed!==8)process.exitCode=1;fs.rmSync(dir,{recursive:true,force:true})})().catch(e=>{console.error(e);process.exitCode=1})